config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "home#index"
  get "/customer/register", to: "customer_registrations#new", as: "customer_register"
  post "/customer/register", to: "customer_registrations#create"

  get "/customer/login", to: "customer_sessions#new", as: "customer_login"
  post "/customer/login", to: "customer_sessions#create"
  get "/customer/logout", to: "customer_sessions#destroy", as: "customer_logout"

  get "/official/register", to: "official_registrations#new", as: "official_register"
  post "/official/register", to: "official_registrations#create"

  get "/official/login", to: "official_sessions#new", as: "official_login"
  post "/official/login", to: "official_sessions#create"
  get "/official/logout", to: "official_sessions#destroy", as: "official_logout"

  get "/customer/dashboard", to: "customers#index", as: "customer_dashboard"

  get "/customer/connections", to: "customer_connections#index", as: "customer_connections"
  get "/customer/connections/new", to: "customer_connections#new", as: "customer_connections_new"
  post "/customer/connections/new", to: "customer_connections#create"
  get "/customer/connections/:connection_id", to: "customer_connections#show", as: "customer_connection"

  get "/customer/connections/:connection_id/bills/new", to: "customer_connection_bills#new", as: "customer_connection_bills_new"
  post "/customer/connections/:connection_id/bills/new", to: "customer_connection_bills#create"
  get "/customer/connections/:connection_id/bills/:bill_id", to: "customer_connection_bills#show", as: "customer_connection_bill"

  get "/customer/connections/:connection_id/grievances/new", to: "customer_connection_grievances#new", as: "customer_connection_grievances_new"
  post "/customer/connections/:connection_id/grievances/new", to: "customer_connection_grievances#create"
  get "/customer/connections/:connection_id/grievances/:grievance_id", to: "customer_connection_grievances#show", as: "customer_connection_grievance"

  get "/official/dashboard", to: "officials#index", as: "official_dashboard"

  get "/official/bills", to: "official_bills#index", as: "official_bills"
  get "/official/bills/:bill_id", to: "official_bills#show", as: "official_bill"
  get "/official/bills/:bill_id/edit",to: "official_bills#edit", as: "official_bill_edit"
  patch "/official/bills/:bill_id", to: "official_bills#update", as: "official_bill_patch"

  get "/official/grievances", to: "official_grievances#index", as: "official_grievances"
  get "/official/grievances/:grievance_id", to: "official_grievances#show", as: "official_grievance"
  get "/official/grievances/:grievance_id/edit", to:"official_grievances#edit" ,as: "official_grievance_edit"
  patch "/official/grievances/:grievance_id", to: "official_grievances#update" , as: "official_grievance_patch"
end

app/views/shared/_flash.html.erb
<% if flash[:success] %>
  <div class="alert alert-success mt-4" role="alert">
    <%= flash[:success] %>
  </div>
<% end %>
<% if flash[:info] %>
  <div class="alert alert-info mt-4" role="alert">
    <%= flash[:info] %>
  </div>
<% end %>
<% if flash[:warning] %>
  <div class="alert alert-warning mt-4" role="alert">
    <%= flash[:warning] %>
  </div>
<% end %>
<% if flash[:danger] %>
  <div class="alert alert-danger mt-4" role="alert">
    <%= flash[:danger] %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-md navbar-light bg-transparent rounded-1">
  <div class="container">
    <a class="navbar-brand" href="<%= root_path %>"><%= image_tag "logo-full.svg", height: "24" %></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
      data-bs-target="#navbar-1" aria-controls="navbar-1" aria-expanded="false"
      aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbar-1">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="<%= root_path %>">Home</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="registerDropdown"
            role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Register
          </a>
          <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="registerDropdown">
            <li><a class="dropdown-item" href="<%= customer_register_path %>">Customer</a></li>
            <li><a class="dropdown-item" href="<%= official_register_path %>">Official</a></li>
          </ul>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="loginDropdown"
            role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Login
          </a>
          <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="loginDropdown">
            <li><a class="dropdown-item" href="<%= customer_login_path %>">Customer</a></li>
            <li><a class="dropdown-item" href="<%= official_login_path %>">Official</a></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_sidebar_customer.html.erb
<aside class="sidebar sidebar-default navs-rounded-all">
  <div class="sidebar-header d-flex align-items-center justify-content-start">
    <a class="navbar-brand" href="<%= customer_dashboard_path %>"><%= image_tag "logo-square.svg", height: "30" %></a>
    <div class="sidebar-toggle" data-toggle="sidebar" data-active="true">
      <i class="icon">
        <svg width="20" height="20" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
          <path d="M4.25 12.2744L19.25 12.2744" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path>
          <path d="M10.2998 18.2988L4.2498 12.2748L10.2998 6.24976" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path>
        </svg>
      </i>
    </div>
  </div>
  <div class="sidebar-body pt-0 data-scrollbar" data-scrollbar="true" tabindex="-1" style="overflow: hidden; outline: none;"><div class="scroll-content">
      <div class="sidebar-list">
          <!-- Sidebar Menu Start -->
          <ul class="navbar-nav iq-main-menu" id="sidebar-menu">
              <li class="nav-item">
                  <a class="nav-link" aria-current="page" href="<%= customer_dashboard_path %>">
                      <i class="icon">
                          <svg width="20" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                              <path opacity="0.4" d="M16.0756 2H19.4616C20.8639 2 22.0001 3.14585 22.0001 4.55996V7.97452C22.0001 9.38864 20.8639 10.5345 19.4616 10.5345H16.0756C14.6734 10.5345 13.5371 9.38864 13.5371 7.97452V4.55996C13.5371 3.14585 14.6734 2 16.0756 2Z" fill="currentColor"></path>
                              <path fill-rule="evenodd" clip-rule="evenodd" d="M4.53852 2H7.92449C9.32676 2 10.463 3.14585 10.463 4.55996V7.97452C10.463 9.38864 9.32676 10.5345 7.92449 10.5345H4.53852C3.13626 10.5345 2 9.38864 2 7.97452V4.55996C2 3.14585 3.13626 2 4.53852 2ZM4.53852 13.4655H7.92449C9.32676 13.4655 10.463 14.6114 10.463 16.0255V19.44C10.463 20.8532 9.32676 22 7.92449 22H4.53852C3.13626 22 2 20.8532 2 19.44V16.0255C2 14.6114 3.13626 13.4655 4.53852 13.4655ZM19.4615 13.4655H16.0755C14.6732 13.4655 13.537 14.6114 13.537 16.0255V19.44C13.537 20.8532 14.6732 22 16.0755 22H19.4615C20.8637 22 22 20.8532 22 19.44V16.0255C22 14.6114 20.8637 13.4655 19.4615 13.4655Z" fill="currentColor"></path>
                          </svg>
                      </i>
                      <span class="item-name align-self-center">Dashboard</span>
                  </a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" aria-current="page" href="<%= customer_connections_new_path %>">
                      <i class="icon">
                        <svg width="20" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                          <path d="M22.8388 2.69682H21.2848V1.17751C21.2848 0.528873 20.7646 0 20.1237 0C19.4841 0 18.9625 0.528873 18.9625 1.17751V2.69682H17.4112C16.7702 2.69682 16.25 3.22569 16.25 3.87435C16.25 4.5229 16.7702 5.05184 17.4112 5.05184H18.9625V6.57252C18.9625 7.22119 19.4841 7.75 20.1237 7.75C20.7646 7.75 21.2848 7.22119 21.2848 6.57252V5.05184H22.8388C23.4784 5.05184 24 4.5229 24 3.87435C24 3.22569 23.4784 2.69682 22.8388 2.69682Z" fill="currentColor"/>
                          <path d="M8.76283 4.68914C8.47913 4.74133 8.18478 4.79569 7.89106 4.92937C7.18839 5.29356 6.75001 6.30245 6.75001 7.38404C6.74875 7.98743 6.95792 8.7506 7.1696 9.18323L8.8599 12.7696V14.647C8.8599 16.0287 9.45923 17.1397 10.3241 17.3495C11.1545 17.5278 12.7221 17.5713 13.6358 17.3495C14.5495 17.1571 15.1401 16.0961 15.1401 14.647V12.7696L16.8554 9.11365C17.039 8.73859 17.2494 8.07659 17.2494 7.46781C17.25 7.42867 17.25 7.39388 17.25 7.35909C17.25 6.25679 16.7953 5.286 16.0945 4.92181C15.7964 4.78378 15.5171 4.73594 15.2472 4.68914L14.9798 4.64026C14.1124 4.45325 9.88196 4.45325 9.02085 4.64026L8.76283 4.68914Z" fill="currentColor"/>
                          <path opacity="0.4" d="M15 1.18065V6.31935C15 6.55707 14.552 6.75 14 6.75C13.448 6.75 13 6.55707 13 6.31935V1.18065C13 0.942929 13.448 0.75 14 0.75C14.552 0.75 15 0.942929 15 1.18065Z" fill="currentColor"/>
                          <path opacity="0.4" d="M11 1.18065V6.31935C11 6.55707 10.552 6.75 10 6.75C9.448 6.75 9 6.55707 9 6.31935V1.18065C9 0.942929 9.448 0.75 10 0.75C10.552 0.75 11 0.942929 11 1.18065Z" fill="currentColor"/>
                          <path opacity="0.4" d="M13 18.3948V23.1052C13 23.3231 12.552 23.5 12 23.5C11.448 23.5 11 23.3231 11 23.1052V18.3948C11 18.1769 11.448 18 12 18C12.552 18 13 18.1769 13 18.3948Z" fill="currentColor"/>
                        </svg>
                      </i>
                      <span class="item-name align-self-center">New Connection</span>
                  </a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" aria-current="page" href="<%= customer_connections_path %>">
                      <i class="icon">
                        <svg width="20" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                          <path d="M8.76283 4.68914C8.47913 4.74133 8.18478 4.79569 7.89106 4.92937C7.18839 5.29356 6.75001 6.30245 6.75001 7.38404C6.74875 7.98743 6.95792 8.7506 7.1696 9.18323L8.8599 12.7696V14.647C8.8599 16.0287 9.45923 17.1397 10.3241 17.3495C11.1545 17.5278 12.7221 17.5713 13.6358 17.3495C14.5495 17.1571 15.1401 16.0961 15.1401 14.647V12.7696L16.8554 9.11365C17.039 8.73859 17.2494 8.07659 17.2494 7.46781C17.25 7.42867 17.25 7.39388 17.25 7.35909C17.25 6.25679 16.7953 5.286 16.0945 4.92181C15.7964 4.78378 15.5171 4.73594 15.2472 4.68914L14.9798 4.64026C14.1124 4.45325 9.88196 4.45325 9.02085 4.64026L8.76283 4.68914Z" fill="currentColor"/>
                          <path opacity="0.4" d="M15 1.18065V6.31935C15 6.55707 14.552 6.75 14 6.75C13.448 6.75 13 6.55707 13 6.31935V1.18065C13 0.942929 13.448 0.75 14 0.75C14.552 0.75 15 0.942929 15 1.18065Z" fill="currentColor"/>
                          <path opacity="0.4" d="M11 1.18065V6.31935C11 6.55707 10.552 6.75 10 6.75C9.448 6.75 9 6.55707 9 6.31935V1.18065C9 0.942929 9.448 0.75 10 0.75C10.552 0.75 11 0.942929 11 1.18065Z" fill="currentColor"/>
                          <path opacity="0.4" fill-rule="evenodd" clip-rule="evenodd" d="M21.75 3.07299V5.85367L21.7703 5.85789L21.974 5.89549L21.9783 5.89623C22.1826 5.932 22.3941 5.96902 22.6196 6.07447C23.1536 6.35462 23.5 7.10138 23.5 7.9493C23.5 7.97606 23.5 8.00282 23.4995 8.03293C23.4995 8.50122 23.3392 9.01045 23.1994 9.29896L21.8924 12.1112V13.5554C21.8924 14.6701 21.4425 15.4862 20.7463 15.6343C20.0502 15.8049 18.8558 15.7714 18.2231 15.6343C17.5642 15.4729 17.1075 14.6182 17.1075 13.5554V12.1112L15.8197 9.35249C15.6584 9.01969 15.4991 8.43264 15.5 7.96849C15.5 7.1365 15.834 6.36043 16.3694 6.08029C16.5932 5.97745 16.8174 5.93563 17.0336 5.89549L17.2302 5.85789C17.2365 5.85649 17.2431 5.85511 17.25 5.85374V3.07299C17.25 2.8947 17.586 2.75 18 2.75C18.414 2.75 18.75 2.8947 18.75 3.07299V5.75735C19.2346 5.74753 19.7652 5.74755 20.25 5.75741V3.07299C20.25 2.8947 20.586 2.75 21 2.75C21.414 2.75 21.75 2.8947 21.75 3.07299Z" fill="currentColor"/>
                          <path opacity="0.4" fill-rule="evenodd" clip-rule="evenodd" d="M6.75 3.07299V5.85367L6.77031 5.85789L6.97404 5.89549L6.9783 5.89623L6.9783 5.89623C7.18263 5.932 7.3941 5.96903 7.61964 6.07447C8.1536 6.35462 8.5 7.10138 8.5 7.9493C8.5 7.97606 8.5 8.00282 8.49951 8.03293C8.49951 8.50122 8.3392 9.01045 8.19938 9.29896L6.89244 12.1112V13.5554C6.89244 14.6701 6.44249 15.4862 5.74631 15.6343C5.05018 15.8049 3.85582 15.7714 3.22313 15.6343C2.56418 15.4729 2.10754 14.6182 2.10754 13.5554V12.1112L0.819698 9.35249C0.658418 9.01969 0.499049 8.43264 0.500004 7.96849C0.500004 7.1365 0.834013 6.36043 1.36938 6.08029C1.59317 5.97745 1.81743 5.93563 2.03358 5.89549L2.23017 5.85789C2.23654 5.85649 2.24315 5.85511 2.25 5.85374V3.07299C2.25 2.8947 2.586 2.75 3 2.75C3.414 2.75 3.75 2.8947 3.75 3.07299V5.75735C4.23463 5.74753 4.76523 5.74755 5.25 5.75741V3.07299C5.25 2.8947 5.586 2.75 6 2.75C6.414 2.75 6.75 2.8947 6.75 3.07299Z" fill="currentColor"/>
                          <path opacity="0.4" d="M13 18.3948V23.1052C13 23.3231 12.552 23.5 12 23.5C11.448 23.5 11 23.3231 11 23.1052V18.3948C11 18.1769 11.448 18 12 18C12.552 18 13 18.1769 13 18.3948Z" fill="currentColor"/>
                          <path opacity="0.4" d="M20.25 16.305V19.945C20.25 20.1133 19.914 20.25 19.5 20.25C19.086 20.25 18.75 20.1133 18.75 19.945V16.305C18.75 16.1367 19.086 16 19.5 16C19.914 16 20.25 16.1367 20.25 16.305Z" fill="currentColor"/>
                          <path opacity="0.4" d="M5.25 16.305V19.945C5.25 20.1133 4.914 20.25 4.5 20.25C4.086 20.25 3.75 20.1133 3.75 19.945V16.305C3.75 16.1367 4.086 16 4.5 16C4.914 16 5.25 16.1367 5.25 16.305Z" fill="currentColor"/>
                        </svg>
                      </i>
                      <span class="item-name align-self-center">Connections</span>
                  </a>
              </li>
              <li><hr class="hr-horizontal"></li>
              <li class="nav-item">
                  <a class="nav-link" aria-current="page" href="<%= customer_logout_path %>">
                      <i class="icon">
                        <svg width="20" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                          <path opacity="0.4" d="M2 6.447C2 3.996 4.03024 2 6.52453 2H11.4856C13.9748 2 16 3.99 16 6.437V17.553C16 20.005 13.9698 22 11.4744 22H6.51537C4.02515 22 2 20.01 2 17.563V16.623V6.447Z" fill="currentColor"></path>
                          <path d="M21.7787 11.4548L18.9329 8.5458C18.6388 8.2458 18.1655 8.2458 17.8723 8.5478C17.5802 8.8498 17.5811 9.3368 17.8743 9.6368L19.4335 11.2298H17.9386H9.54826C9.13434 11.2298 8.79834 11.5748 8.79834 11.9998C8.79834 12.4258 9.13434 12.7698 9.54826 12.7698H19.4335L17.8743 14.3628C17.5811 14.6628 17.5802 15.1498 17.8723 15.4518C18.0194 15.6028 18.2113 15.6788 18.4041 15.6788C18.595 15.6788 18.7868 15.6028 18.9329 15.4538L21.7787 12.5458C21.9199 12.4008 21.9998 12.2048 21.9998 11.9998C21.9998 11.7958 21.9199 11.5998 21.7787 11.4548Z" fill="currentColor"></path>
                        </svg>
                      </i>
                      <span class="item-name align-self-center">Logout</span>
                  </a>
              </li>
          </ul>
        </div>
      </div>
      <div class="scrollbar-track scrollbar-track-x" style="display: none;">
        <div class="scrollbar-thumb scrollbar-thumb-x" style="width: 259px; transform: translate3d(0px, 0px, 0px);"></div>
      </div>
      <div class="scrollbar-track scrollbar-track-y" style="display: block;">
        <div class="scrollbar-thumb scrollbar-thumb-y" style="height: 654.242px; transform: translate3d(0px, 0px, 0px);"></div>
      </div>
    </div>
  <div class="sidebar-footer"></div>
</aside>

app/views/shared/_sidebar_official.html.erb
<aside class="sidebar sidebar-default navs-rounded-all">
  <div class="sidebar-header d-flex align-items-center justify-content-start">
    <a class="navbar-brand" href="<%= official_dashboard_path %>"><%= image_tag "logo-square.svg", height: "30" %></a>
    <div class="sidebar-toggle" data-toggle="sidebar" data-active="true">
      <i class="icon">
        <svg width="20" height="20" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
          <path d="M4.25 12.2744L19.25 12.2744" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path>
          <path d="M10.2998 18.2988L4.2498 12.2748L10.2998 6.24976" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path>
        </svg>
      </i>
    </div>
  </div>
  <div class="sidebar-body pt-0 data-scrollbar" data-scrollbar="true" tabindex="-1" style="overflow: hidden; outline: none;"><div class="scroll-content">
      <div class="sidebar-list">
          <!-- Sidebar Menu Start -->
          <ul class="navbar-nav iq-main-menu" id="sidebar-menu">
              <li class="nav-item">
                  <a class="nav-link" aria-current="page" href="<%= official_dashboard_path %>">
                      <i class="icon">
                          <svg width="20" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                              <path opacity="0.4" d="M16.0756 2H19.4616C20.8639 2 22.0001 3.14585 22.0001 4.55996V7.97452C22.0001 9.38864 20.8639 10.5345 19.4616 10.5345H16.0756C14.6734 10.5345 13.5371 9.38864 13.5371 7.97452V4.55996C13.5371 3.14585 14.6734 2 16.0756 2Z" fill="currentColor"></path>
                              <path fill-rule="evenodd" clip-rule="evenodd" d="M4.53852 2H7.92449C9.32676 2 10.463 3.14585 10.463 4.55996V7.97452C10.463 9.38864 9.32676 10.5345 7.92449 10.5345H4.53852C3.13626 10.5345 2 9.38864 2 7.97452V4.55996C2 3.14585 3.13626 2 4.53852 2ZM4.53852 13.4655H7.92449C9.32676 13.4655 10.463 14.6114 10.463 16.0255V19.44C10.463 20.8532 9.32676 22 7.92449 22H4.53852C3.13626 22 2 20.8532 2 19.44V16.0255C2 14.6114 3.13626 13.4655 4.53852 13.4655ZM19.4615 13.4655H16.0755C14.6732 13.4655 13.537 14.6114 13.537 16.0255V19.44C13.537 20.8532 14.6732 22 16.0755 22H19.4615C20.8637 22 22 20.8532 22 19.44V16.0255C22 14.6114 20.8637 13.4655 19.4615 13.4655Z" fill="currentColor"></path>
                          </svg>
                      </i>
                      <span class="item-name">Dashboard</span>
                  </a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" aria-current="page" href="<%= official_bills_path %>">
                      <i class="icon">
                          <svg width="20" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">                                <path opacity="0.4" d="M18.8088 9.021C18.3573 9.021 17.7592 9.011 17.0146 9.011C15.1987 9.011 13.7055 7.508 13.7055 5.675V2.459C13.7055 2.206 13.5036 2 13.253 2H7.96363C5.49517 2 3.5 4.026 3.5 6.509V17.284C3.5 19.889 5.59022 22 8.16958 22H16.0463C18.5058 22 20.5 19.987 20.5 17.502V9.471C20.5 9.217 20.299 9.012 20.0475 9.013C19.6247 9.016 19.1177 9.021 18.8088 9.021Z" fill="currentColor"></path>                                <path opacity="0.4" d="M16.0842 2.56737C15.7852 2.25637 15.2632 2.47037 15.2632 2.90137V5.53837C15.2632 6.64437 16.1742 7.55437 17.2802 7.55437C17.9772 7.56237 18.9452 7.56437 19.7672 7.56237C20.1882 7.56137 20.4022 7.05837 20.1102 6.75437C19.0552 5.65737 17.1662 3.69137 16.0842 2.56737Z" fill="currentColor"></path>                                <path fill-rule="evenodd" clip-rule="evenodd" d="M8.97398 11.3877H12.359C12.77 11.3877 13.104 11.0547 13.104 10.6437C13.104 10.2327 12.77 9.89868 12.359 9.89868H8.97398C8.56298 9.89868 8.22998 10.2327 8.22998 10.6437C8.22998 11.0547 8.56298 11.3877 8.97398 11.3877ZM8.97408 16.3819H14.4181C14.8291 16.3819 15.1631 16.0489 15.1631 15.6379C15.1631 15.2269 14.8291 14.8929 14.4181 14.8929H8.97408C8.56308 14.8929 8.23008 15.2269 8.23008 15.6379C8.23008 16.0489 8.56308 16.3819 8.97408 16.3819Z" fill="currentColor"></path>                                </svg>        
                      </i>
                      <span class="item-name">Bills</span>
                  </a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" aria-current="page" href="<%= official_grievances_path %>">
                      <i class="icon">
                                                          <svg width="20" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">                                <path opacity="0.4" d="M22 11.9998C22 17.5238 17.523 21.9998 12 21.9998C6.477 21.9998 2 17.5238 2 11.9998C2 6.47776 6.477 1.99976 12 1.99976C17.523 1.99976 22 6.47776 22 11.9998Z" fill="currentColor"></path>                                <path fill-rule="evenodd" clip-rule="evenodd" d="M12.8701 12.6307C12.8701 13.1127 12.4771 13.5057 11.9951 13.5057C11.5131 13.5057 11.1201 13.1127 11.1201 12.6307V8.21069C11.1201 7.72869 11.5131 7.33569 11.9951 7.33569C12.4771 7.33569 12.8701 7.72869 12.8701 8.21069V12.6307ZM11.1251 15.8035C11.1251 15.3215 11.5161 14.9285 11.9951 14.9285C12.4881 14.9285 12.8801 15.3215 12.8801 15.8035C12.8801 16.2855 12.4881 16.6785 12.0051 16.6785C11.5201 16.6785 11.1251 16.2855 11.1251 15.8035Z" fill="currentColor"></path>                                </svg>                            
                      </i>
                      <span class="item-name">Grievances</span>
                  </a>
              </li>
              <li><hr class="hr-horizontal"></li>
              <li class="nav-item">
                  <a class="nav-link" aria-current="page" href="<%= official_logout_path %>">
                      <i class="icon">
                                                         <svg width="20" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">                                <path opacity="0.4" d="M2 6.447C2 3.996 4.03024 2 6.52453 2H11.4856C13.9748 2 16 3.99 16 6.437V17.553C16 20.005 13.9698 22 11.4744 22H6.51537C4.02515 22 2 20.01 2 17.563V16.623V6.447Z" fill="currentColor"></path>                                <path d="M21.7787 11.4548L18.9329 8.5458C18.6388 8.2458 18.1655 8.2458 17.8723 8.5478C17.5802 8.8498 17.5811 9.3368 17.8743 9.6368L19.4335 11.2298H17.9386H9.54826C9.13434 11.2298 8.79834 11.5748 8.79834 11.9998C8.79834 12.4258 9.13434 12.7698 9.54826 12.7698H19.4335L17.8743 14.3628C17.5811 14.6628 17.5802 15.1498 17.8723 15.4518C18.0194 15.6028 18.2113 15.6788 18.4041 15.6788C18.595 15.6788 18.7868 15.6028 18.9329 15.4538L21.7787 12.5458C21.9199 12.4008 21.9998 12.2048 21.9998 11.9998C21.9998 11.7958 21.9199 11.5998 21.7787 11.4548Z" fill="currentColor"></path>                                </svg>                            
                      </i>
                      <span class="item-name">Logout</span>
                  </a>
              </li>
          </ul>
        </div>
      </div>
      <div class="scrollbar-track scrollbar-track-x" style="display: none;">
        <div class="scrollbar-thumb scrollbar-thumb-x" style="width: 259px; transform: translate3d(0px, 0px, 0px);"></div>
      </div>
      <div class="scrollbar-track scrollbar-track-y" style="display: block;">
        <div class="scrollbar-thumb scrollbar-thumb-y" style="height: 654.242px; transform: translate3d(0px, 0px, 0px);"></div>
      </div>
    </div>
  <div class="sidebar-footer"></div>
</aside>