config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "home#index"
  get "/customer/register", to: "customer_registrations#new", as: "customer_register"
  post "/customer/register", to: "customer_registrations#create"

  get "/customer/login", to: "customer_sessions#new", as: "customer_login"
  post "/customer/login", to: "customer_sessions#create"
  get "/customer/logout", to: "customer_sessions#destroy", as: "customer_logout"

  get "/official/register", to: "official_registrations#new", as: "official_register"
  post "/official/register", to: "official_registrations#create"

  get "/official/login", to: "official_sessions#new", as: "official_login"
  post "/official/login", to: "official_sessions#create"
  get "/official/logout", to: "official_sessions#destroy", as: "official_logout"

  get "/customer/dashboard", to: "customers#index", as: "customer_dashboard"

  get "/customer/connections", to: "customer_connections#index", as: "customer_connections"
  get "/customer/connections/new", to: "customer_connections#new", as: "customer_connections_new"
  post "/customer/connections/new", to: "customer_connections#create"
  get "/customer/connections/:connection_id", to: "customer_connections#show", as: "customer_connection"

  get "/customer/connections/:connection_id/bills/new", to: "customer_connection_bills#new", as: "customer_connection_bills_new"
  post "/customer/connections/:connection_id/bills/new", to: "customer_connection_bills#create"
  get "/customer/connections/:connection_id/bills/:bill_id", to: "customer_connection_bills#show", as: "customer_connection_bill"

  get "/customer/connections/:connection_id/grievances/new", to: "customer_connection_grievances#new", as: "customer_connection_grievances_new"
  post "/customer/connections/:connection_id/grievances/new", to: "customer_connection_grievances#create"
  get "/customer/connections/:connection_id/grievances/:grievance_id", to: "customer_connection_grievances#show", as: "customer_connection_grievance"

  get "/official/dashboard", to: "officials#index", as: "official_dashboard"

  get "/official/bills", to: "official_bills#index", as: "official_bills"
  get "/official/bills/:bill_id", to: "official_bills#show", as: "official_bill"
  get "/official/bills/:bill_id/edit",to: "official_bills#edit", as: "official_bill_edit"
  patch "/official/bills/:bill_id", to: "official_bills#update", as: "official_bill_patch"

  get "/official/grievances", to: "official_grievances#index", as: "official_grievances"
  get "/official/grievances/:grievance_id", to: "official_grievances#show", as: "official_grievance"
  get "/official/grievances/:grievance_id/edit", to:"official_grievances#edit" ,as: "official_grievance_edit"
  patch "/official/grievances/:grievance_id", to: "official_grievances#update" , as: "official_grievance_patch"
end

app/controllers/official_bills_controller.rb
class OfficialBillsController < ApplicationController
  before_action :require_official_signed_in

  layout "official"

  def index
    @connections = Connection.where(area: Current.official.area )
    @bills = Bill.where(connection: [@connections]).order(created_at: :desc)
  end

  def show
    @bill = Bill.find(params[:bill_id])
  end

  def edit
    @bill = Bill.find(params[:bill_id])
  end

  def update
    @bill = Bill.find(params[:bill_id])

    if @bill.update(bill_params)
      unit = @bill.curr_reading - @bill.prev_reading
      if @bill.update(units: unit)
        amount = (@bill.connection.rate) * @bill.units
      end
      if @bill.update(amount: amount)
        @bill.update(status: "Bill Generated")
        @bill.official = Current.official
      end
      redirect_to official_bill_path(@bill.id)
    else
      render :edit
    end
  end

  private

  def bill_params
    params.require(:bill).permit(:prev_reading, :curr_reading, :status, :units, :amount)
  end
end

app/views/official_bills/edit.html.erb
<div class="card aos-init aos-animate" data-aos="fade-up" data-aos-delay="800">
  <div class="card-header">
    <h4 class="card-title">Bill Details</h4>
  </div>
  <div class="card-body">
    <div class="row">
      <div class="col-md-7 col-lg-8">
        <div class="mb-3">
          <label class="text-muted fw-bold">Connection Details</label>
          <p class="text-dark"><%= @bill.connection.name %> ( <%= @bill.connection.phase %> Phase,  <%= @bill.connection.connection_type %>)</p>
        </div>
        <div class="mb-3">
          <label class="text-muted fw-bold">Billing Date</label>
          <p class="text-dark"><%= @bill.created_at.to_date %></p>
        </div>
        <div class="mb-3">
          <label class="text-muted fw-bold">Previous Reading</label>
          <p class="text-dark"><%= @bill.prev_reading %></p>
        </div>
        <div class="mb-3">
          <label class="text-muted fw-bold">Current Reading</label>
          <p class="text-dark"><%= @bill.curr_reading || "N/A" %></p>
        </div>
        <div class="mb-3">
          <label class="text-muted fw-bold">Unit Consumption</label>
          <p class="text-dark"><%= @bill.units || "N/A" %></p>
        </div>
        <div class="mb-3">
          <label class="text-muted fw-bold">Consumption Rate</label>
          <p class="text-dark">₹<%= @bill.connection.rate %>/unit</p>
        </div>
        <div class="mb-3">
          <label class="text-muted fw-bold">Payable Amount</label>
          <p class="text-dark"><%= @bill.amount || "N/A" %></p>
        </div>
        <div class="mb-3">
          <label class="text-muted fw-bold">Status</label>
          <p class="text-dark"><%= @bill.status || "N/A" %></p>
        </div>
      </div>
      <div class="col-md-5 col-lg-4">
        <%= image_tag @bill.image, class: "img-thumbnail" %>
      </div>
    </div>
  </div>
</div>


<div class="row justify-content-center">
  <div >
    <div class="card">
      
      <div class="card-body">
        <%= form_with model: @bill, url: official_bill_patch_path do |form| %>
          <div class="form-group">
          <div class="text-dark">
            <%= form.label :Current_Reading %>
            <%= form.number_field :curr_reading, class: "form-control" %>
          </div>
          </div>
          <div class="d-flex justify-content-center">
            <%= form.submit "Generate Bill", class: "btn btn-primary" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
</div>

app/views/official_bills/index.html.erb
<div class="card aos-init aos-animate" data-aos="fade-up" data-aos-delay="800">
  <div class="card-header">
    <h4 class="card-title">Bills</h4>
  </div>
  <div class="card-body">
    <% if @bills.length > 0 %>
      <table class="table table-striped table-hover table responsive">
        <tr>
          <th scope="col">Connection</th>
          <th scope="col">Date</th>
          <th scope="col">Units</th>
          <th scope="col">Amount</th>
          <th scope="col">Status</th>
        <tr>
        <% @bills.each do |bill| %>
         <tr style="cursor: pointer;" onclick="location.href='<%= bill.status == "Bill Generated" ? official_bill_path(bill.id) : official_bill_edit_path(bill.id) %>';">
            <td><%= bill.connection.name %></td>
            <td><%= bill.created_at.strftime("%b %d, %Y") %></td>
            <td><%= bill.units %></td>
            <td><%= bill.amount %></td>
            <td><%= bill.status %></td>
          </tr>
        <% end %>
      </div>
    <% else %>
      <diV class="my-4 d-flex align-items-center justify-content-center">
        <h5 class="text-muted text-center">No bills generated yet!</h5>
      </div>
    <% end %>
  </div>
</div>

app/views/official_bills/show.html.erb
<div class="card aos-init aos-animate" data-aos="fade-up" data-aos-delay="800">
  <div class="card-header">
    <h4 class="card-title">Bill Details</h4>
  </div>
  <div class="card-body">
    <div class="row">
      <div class="col-md-7 col-lg-8">
      <div class="mb-3">
          <label class="text-muted fw-bold">Connection Details</label>
          <p class="text-dark"><%= @bill.connection.name %> ( <%= @bill.connection.phase %> Phase,  <%= @bill.connection.connection_type %> )</p>
        </div>
        <div class="mb-3">
          <label class="text-muted fw-bold">Billing Date</label>
          <p class="text-dark"><%= @bill.created_at.to_date %></p>
        </div>
        <div class="mb-3">
          <label class="text-muted fw-bold">Previous Reading</label>
          <p class="text-dark"><%= @bill.prev_reading %></p>
        </div>
        <div class="mb-3">
          <label class="text-muted fw-bold">Current Reading</label>
          <p class="text-dark"><%= @bill.curr_reading || "N/A" %></p>
        </div>
        <div class="mb-3">
          <label class="text-muted fw-bold">Unit Consumption</label>
          <p class="text-dark"><%= @bill.units || "N/A" %></p>
        </div>
        <div class="mb-3">
          <label class="text-muted fw-bold">Consumption Rate</label>
          <p class="text-dark">₹<%= @bill.connection.rate %>/unit</p>
        </div>
        <div class="mb-3">
          <label class="text-muted fw-bold">Payable Amount</label>
          <p class="text-dark"> <%= number_to_currency(@bill.amount, unit: "₹") || "N/A" %></p>
        </div>
        <div class="mb-3">
          <label class="text-muted fw-bold">Status</label>
          <p class="text-dark"><%= @bill.status || "N/A" %></p>
        </div>
      </div>
      <div class="col-md-5 col-lg-4">
        <%= image_tag @bill.image, class: "img-thumbnail" %>
      </div>
    </div>
  </div>
</div>
</div>