config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "home#index"
  get "/customer/register", to: "customer_registrations#new", as: "customer_register"
  post "/customer/register", to: "customer_registrations#create"

  get "/customer/login", to: "customer_sessions#new", as: "customer_login"
  post "/customer/login", to: "customer_sessions#create"
  get "/customer/logout", to: "customer_sessions#destroy", as: "customer_logout"

  get "/official/register", to: "official_registrations#new", as: "official_register"
  post "/official/register", to: "official_registrations#create"

  get "/official/login", to: "official_sessions#new", as: "official_login"
  post "/official/login", to: "official_sessions#create"
  get "/official/logout", to: "official_sessions#destroy", as: "official_logout"

  get "/customer/dashboard", to: "customers#index", as: "customer_dashboard"

  get "/customer/connections", to: "customer_connections#index", as: "customer_connections"
  get "/customer/connections/new", to: "customer_connections#new", as: "customer_connections_new"
  post "/customer/connections/new", to: "customer_connections#create"
  get "/customer/connections/:connection_id", to: "customer_connections#show", as: "customer_connection"

  get "/customer/connections/:connection_id/bills/new", to: "customer_connection_bills#new", as: "customer_connection_bills_new"
  post "/customer/connections/:connection_id/bills/new", to: "customer_connection_bills#create"
  get "/customer/connections/:connection_id/bills/:bill_id", to: "customer_connection_bills#show", as: "customer_connection_bill"

  get "/customer/connections/:connection_id/grievances/new", to: "customer_connection_grievances#new", as: "customer_connection_grievances_new"
  post "/customer/connections/:connection_id/grievances/new", to: "customer_connection_grievances#create"
  get "/customer/connections/:connection_id/grievances/:grievance_id", to: "customer_connection_grievances#show", as: "customer_connection_grievance"

  get "/official/dashboard", to: "officials#index", as: "official_dashboard"

  get "/official/bills", to: "official_bills#index", as: "official_bills"
  get "/official/bills/:bill_id", to: "official_bills#show", as: "official_bill"
  get "/official/bills/:bill_id/edit",to: "official_bills#edit", as: "official_bill_edit"
  patch "/official/bills/:bill_id", to: "official_bills#update", as: "official_bill_patch"

  get "/official/grievances", to: "official_grievances#index", as: "official_grievances"
  get "/official/grievances/:grievance_id", to: "official_grievances#show", as: "official_grievance"
  get "/official/grievances/:grievance_id/edit", to:"official_grievances#edit" ,as: "official_grievance_edit"
  patch "/official/grievances/:grievance_id", to: "official_grievances#update" , as: "official_grievance_patch"
end

app/controllers/customer_connection_grievances_controller.rb
class CustomerConnectionGrievancesController < ApplicationController
  before_action :require_customer_signed_in
  layout "customer"

  def new
    @grievance = Grievance.new
  end

  def create
    connection = Current.customer.connections.find(params[:connection_id])
    @grievance = connection.grievances.create(grievance_params)
    official = Official.find_by(area: connection.area)
    if !official.present?
      redirect_to customer_connection_path(connection.id), flash: { danger: "No official has been allotted to the area yet. Please try again later." }
    end
    @grievance.official = official
    @grievance.status = "Pending"
    if @grievance.save
      redirect_to customer_connection_path(connection.id), flash: { success: "Grievance added successfully" }
    else
      render :new
    end
  end

  def show
    connection = Current.customer.connections.find(params[:connection_id])
    @grievance = connection.grievances.find(params[:grievance_id])
  end

  private

  def grievance_params
    params.require(:grievance).permit(:problem, :description)
  end
end

app/helpers/customer_connection_grievances_helper.rb
module CustomerConnectionGrievancesHelper
end

app/views/customer_connection_grievances/new.html.erb
<div class="row justify-content-center">
  <div class="col-md-10 col-lg-8">
    <div class="card">
      <div class="card-header d-flex justify-content-between">
        <div class="header-title">
          <h4 class="card-title">New Grievance Details</h4>
        </div>
      </div>
      <div class="card-body">
        <%= form_with model: @grievance, url: customer_connection_grievances_new_path do |form| %>
          <div class="form-group">
            <%= form.label :problem %>
            <%= form.text_field :problem, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= form.label :description %>
            <%= form.text_area :description, class: "form-control", rows: "4" %>
          </div>
          <div class="d-flex justify-content-center">
            <%= form.submit "Submit", class: "btn btn-primary" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/customer_connection_grievances/show.html.erb
<div class="row">
  <div class="col">
    <div class="card aos-init aos-animate" data-aos="fade-up" data-aos-delay="800">
      <div class="card-header">
        <h4 class="card-title">Grievance Details</h4>
      </div>
      <div class="card-body">
      <div class="mb-3">
        <label class="text-muted fw-bold">Problem</label>
        <p class="text-dark"><%= @grievance.problem %></p>
      </div>
      <div class="mb-3">
        <label class="text-muted fw-bold">Description</label>
        <p class="text-dark"><%= @grievance.description %></p>
      </div>
      <div class="mb-3">
        <label class="text-muted fw-bold">Status</label>
        <p class="text-dark"><%= @grievance.status %></p>
      </div>
      <div class="mb-3">
        <label class="text-muted fw-bold">Remarks</label>
        <p class="text-dark"><%= @grievance.remarks %></p>
      </div>
      </div>
    </div>
  </div>
  </div>
</div>